export const ALL_PRODUCTS_REQUESTS = 'ALL_PRODUCTS_REQUESTS';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCTS_DETAILS_REQUESTS = 'PRODUCTS_DETAILS_REQUESTS';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'  ;